name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run simple script
      run: echo Kept you waiting, huh?

    - name: Run milti-line script
      run: |
        echo WHY WONT YOU DIE?!
        echo NANOMACHINES, SON!
