name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run simple script
      run: echo Kept you waiting, huh?
    
    - name: Run milti-line script
      run: |
        echo WHY WON'T YOU DIE?!
        echo NANOMACHINES, SON!
